baseURL = "https://z-progandroid.github.io/Hugo_Site/"
languageCode = "en-us"
title = "Portafilo"
theme = "hugo-theme-learn"

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "purple"
  disableLandingPage="flase"
# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]


# Force to have /en/my-page and /fr/my-page routes, even for default language.
defaultContentLanguageInSubdir= true
defaultContentLanguage = "en"

[Languages]
[Languages.en]
title = "My New Hugo Site"
weight = 1
languageName = "English"
landingPageURL = "/Hugo_Site/"
contentDir = 'content/english'
landingPageName = "<i class='fas fa-home'></i> Home"

[Languages.es]
title = "My New Hugo Site es"
weight = 2
contentDir = 'content/spanish'
languageName = "Español"
landingPageURL = "/Hugo_Site/"
landingPageName = "<i class='fas fa-home'></i> Home"